# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

owner: dogchef-be # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Dogchef
    url: https://www.dogchef.com
  - name: Dogchef (My account)
    url: https://www.dogchef.com/en/account
  - name: Dogchef (Signup)
    url: https://www.dogchef.com/en/start
  - name: Dogchef (API)
    url: $DOGCHEF_API_URL
  - name: Dogchef partners
    url: $DOGCHEF_PARTNERS_URL
  - name: ERP
    url: $ERP_URL
  - name: Dogpit
    url: $DOGPIT_URL
  - name: Dogpit-tasks
    url: $DOGPIT_TASKS_URL
  - name: Catchef
    url: $CATCHEF_URL
  - name: Cheapmeat
    url: $CHEAPMEAT_URL
  - name: Dogocook
    url: $DOGOCOOK_URL
  - name: Dogocook (Forum)
    url: $DOGOCOOK_FORUM_URL
  - name: Vetchef (BE)
    url: $VETCHEF_BE_URL
  - name: Vetchef (FR)
    url: $VETCHEF_FR_URL
  - name: Vetchef (LU)
    url: $VETCHEF_LU_URL

status-website:
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime monitor
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: "robots"
      content: "noindex"

status-page:
  robotsText: "User-agent: * \n Disallow: /"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
